MBTI_DATA = {
    "ISTJ": {"nickname": "청렴한 논리주의자", "keywords": ["신중함", "책임감", "체계적"], "strengths": ["계획적", "성실함", "신뢰감"], "weaknesses": ["융통성 부족", "변화 거부"], "compat_best": ["ESFP", "ESTP"], "compat_worst": ["ENFP", "ESFJ"], "jobs": ["회계사", "감사관", "행정직", "군인", "판사"], "hobbies": ["독서", "역사 다큐멘터리 시청", "체스", "정원 가꾸기", "모형 조립"]},
    "ISFJ": {"nickname": "용감한 수호자", "keywords": ["헌신적", "온화함", "책임감"], "strengths": ["배려심", "인내심", "실용성"], "weaknesses": ["자기희생", "변화 스트레스"], "compat_best": ["ESFP", "ESTP"], "compat_worst": ["ENTJ", "ENFP"], "jobs": ["간호사", "사회복지사", "초등교사", "상담사"], "hobbies": ["베이킹", "뜨개질", "사진 정리·앨범 만들기", "가족과 보드게임", "가벼운 등산"]},
    "INFJ": {"nickname": "선의의 옹호자", "keywords": ["통찰력", "이상주의", "공감능력"], "strengths": ["직관력", "헌신", "창의성"], "weaknesses": ["완벽주의", "번아웃 취약"], "compat_best": ["ENFP", "ENTP"], "compat_worst": ["ESTP", "ESFP"], "jobs": ["상담심리사", "작가", "인권활동가", "교사"], "hobbies": ["글쓰기/일기", "명상", "심리학 책 읽기", "영화 감상", "봉사활동"]},
    "INTJ": {"nickname": "용의주도한 전략가", "keywords": ["전략적", "독립적", "분석적"], "strengths": ["장기계획", "논리력", "결단력"], "weaknesses": ["과도한 비판", "감정표현 어려움"], "compat_best": ["ENFP", "ENTP"], "compat_worst": ["ESFP", "ESFJ"], "jobs": ["전략기획가", "과학자", "데이터분석가", "건축가"], "hobbies": ["전략 보드게임", "독서(비문학)", "체스", "코딩/사이드 프로젝트", "다큐멘터리 시청"]},
    "ISTP": {"nickname": "만능 재주꾼", "keywords": ["실용적", "논리적", "독립적"], "strengths": ["문제해결", "적응력", "냉철함"], "weaknesses": ["감정표현 부족", "장기계획 약함"], "compat_best": ["ESFJ", "ESTJ"], "compat_worst": ["ENFJ", "INFJ"], "jobs": ["엔지니어", "정비기술자", "파일럿", "프로그래머"], "hobbies": ["DIY/공예", "자동차·기계 관련 취미", "캠핑", "자전거 라이딩", "게임(퍼즐/전략)"]},
    "ISFP": {"nickname": "호기심 많은 예술가", "keywords": ["예술적", "온화함", "유연함"], "strengths": ["미적감각", "공감력", "적응력"], "weaknesses": ["갈등회피", "계획성 부족"], "compat_best": ["ESFJ", "ESTJ"], "compat_worst": ["ENTJ", "INTJ"], "jobs": ["디자이너", "포토그래퍼", "요리사", "플로리스트"], "hobbies": ["그림 그리기", "사진 촬영", "식물 키우기", "요리", "음악 감상"]},
    "INFP": {"nickname": "열정적인 중재자", "keywords": ["이상주의", "창의적", "공감능력"], "strengths": ["창의성", "가치중심", "공감"], "weaknesses": ["현실감 부족", "비판에 민감"], "compat_best": ["ENFJ", "ENTJ"], "compat_worst": ["ESTJ", "ISTJ"], "jobs": ["작가", "카피라이터", "상담사", "예술가"], "hobbies": ["소설 쓰기", "시 읽기", "음악 감상", "혼자 여행", "다이어리 꾸미기"]},
    "INTP": {"nickname": "논리적인 사색가", "keywords": ["논리적", "독창적", "분석적"], "strengths": ["창의적사고", "논리력", "호기심"], "weaknesses": ["사회성 부족", "실행력 약함"], "compat_best": ["ENTJ", "ENFJ"], "compat_worst": ["ESFJ", "ISFJ"], "jobs": ["연구원", "프로그래머", "철학자", "데이터과학자"], "hobbies": ["과학·철학 서적 읽기", "퍼즐/퀴즈", "새로운 언어 학습", "게임 개발", "온라인 토론"]},
    "ESTP": {"nickname": "모험을 즐기는 사업가", "keywords": ["활동적", "현실적", "사교적"], "strengths": ["실행력", "적응력", "설득력"], "weaknesses": ["충동적", "장기계획 약함"], "compat_best": ["ISFJ", "ISTJ"], "compat_worst": ["INFJ", "INFP"], "jobs": ["영업직", "창업가", "스포츠매니저", "마케터"], "hobbies": ["익스트림 스포츠", "클럽·파티", "여행", "스포츠 관람", "자동차 드라이브"]},
    "ESFP": {"nickname": "자유로운 영혼의 연예인", "keywords": ["사교적", "즐거움추구", "현실적"], "strengths": ["에너지", "친화력", "적응력"], "weaknesses": ["집중력 부족", "계획성 약함"], "compat_best": ["ISTJ", "ISFJ"], "compat_worst": ["INTJ", "INFJ"], "jobs": ["엔터테이너", "이벤트기획자", "영업직", "여행가이드"], "hobbies": ["춤/댄스", "여행", "사진·영상 촬영", "파티 기획", "쇼핑"]},
    "ENFP": {"nickname": "재기발랄한 활동가", "keywords": ["열정적", "창의적", "사교적"], "strengths": ["아이디어", "친화력", "동기부여"], "weaknesses": ["집중력 부족", "쉽게 지침"], "compat_best": ["INTJ", "INFJ"], "compat_worst": ["ISTJ", "ISFJ"], "jobs": ["마케터", "기획자", "상담사", "크리에이터"], "hobbies": ["여행", "새로운 사람 만나기", "창작 활동(글/그림)", "즉흥 여행", "공연 관람"]},
    "ENTP": {"nickname": "뜨거운 논쟁을 즐기는 변론가", "keywords": ["도전적", "창의적", "논리적"], "strengths": ["아이디어", "설득력", "적응력"], "weaknesses": ["끈기부족", "논쟁적"], "compat_best": ["INFJ", "INTJ"], "compat_worst": ["ISFJ", "ISTJ"], "jobs": ["기업가", "변호사", "컨설턴트", "마케터"], "hobbies": ["토론/디베이트", "창업 아이디어 구상", "보드게임", "여행", "새로운 취미 탐색"]},
    "ESTJ": {"nickname": "엄격한 관리자", "keywords": ["체계적", "리더십", "현실적"], "strengths": ["조직력", "결단력", "책임감"], "weaknesses": ["융통성 부족", "고집"], "compat_best": ["ISFP", "ISTP"], "compat_worst": ["INFP", "ISFP"], "jobs": ["관리자", "군인", "판사", "재무관리자"], "hobbies": ["스포츠 동호회", "재정 관리/투자", "리더십 프로그램 참여", "골프", "자기계발 강의 듣기"]},
    "ESFJ": {"nickname": "사교적인 외교관", "keywords": ["사교적", "배려심", "협동적"], "strengths": ["친화력", "조직력", "책임감"], "weaknesses": ["비판에 민감", "타인의존"], "compat_best": ["ISFP", "ISTP"], "compat_worst": ["INTJ", "ISTJ"], "jobs": ["교사", "간호사", "이벤트기획자", "HR매니저"], "hobbies": ["모임 주최", "요리/베이킹", "봉사활동", "가족 행사 기획", "쇼핑"]},
    "ENFJ": {"nickname": "정의로운 사회운동가", "keywords": ["카리스마", "이상주의", "리더십"], "strengths": ["설득력", "공감능력", "조직력"], "weaknesses": ["자기희생", "비판에 민감"], "compat_best": ["INFP", "ISFP"], "compat_worst": ["ISTP", "INTP"], "jobs": ["교사", "상담사", "HR매니저", "정치인"], "hobbies": ["멘토링/코칭", "공연·연극 관람", "커뮤니티 봉사", "글쓰기", "네트워킹 모임"]},
    "ENTJ": {"nickname": "대담한 통솔자", "keywords": ["리더십", "전략적", "야망적"], "strengths": ["결단력", "추진력", "카리스마"], "weaknesses": ["독선적", "감정소홀"], "compat_best": ["INFP", "ISFP"], "compat_worst": ["ISFJ", "INFJ"], "jobs": ["CEO", "경영컨설턴트", "변호사", "투자은행가"], "hobbies": ["창업/사업 기획", "투자 스터디", "리더십 세미나 참석", "골프", "여행 계획 세우기"]},
}

QUESTIONS = [
    ("친구들과 함께 있으면 에너지가 충전된다.", "E", "I"),
    ("낯선 사람과 대화를 먼저 시작하는 편이다.", "E", "I"),
    ("혼자 있는 시간이 꼭 필요하다.", "I", "E"),
    ("사실과 데이터를 기반으로 판단한다.", "S", "N"),
    ("직관과 가능성을 중요하게 여긴다.", "N", "S"),
    ("구체적인 경험을 신뢰한다.", "S", "N"),
    ("결정을 내릴 때 논리를 우선한다.", "T", "F"),
    ("타인의 감정을 먼저 고려한다.", "F", "T"),
    ("객관적 기준으로 평가하는 것을 선호한다.", "T", "F"),
    ("계획을 세우고 그대로 실행하는 것을 좋아한다.", "J", "P"),
    ("즉흥적으로 행동하는 것을 즐긴다.", "P", "J"),
    ("마감기한 전에 미리 끝내는 편이다.", "J", "P"),
]
