MBTI_DATA = {
    "ISTJ": {"nickname": "청렴한 논리주의자", "keywords": ["신중함", "책임감", "체계적"], "strengths": ["계획적", "성실함", "신뢰감"], "weaknesses": ["융통성 부족", "변화 거부"], "compat_best": ["ESFP", "ESTP"], "compat_worst": ["ENFP", "ESFJ"], "jobs": ["회계사", "감사관", "행정직", "군인", "판사"]},
    "ISFJ": {"nickname": "용감한 수호자", "keywords": ["헌신적", "온화함", "책임감"], "strengths": ["배려심", "인내심", "실용성"], "weaknesses": ["자기희생", "변화 스트레스"], "compat_best": ["ESFP", "ESTP"], "compat_worst": ["ENTJ", "ENFP"], "jobs": ["간호사", "사회복지사", "초등교사", "상담사"]},
    "INFJ": {"nickname": "선의의 옹호자", "keywords": ["통찰력", "이상주의", "공감능력"], "strengths": ["직관력", "헌신", "창의성"], "weaknesses": ["완벽주의", "번아웃 취약"], "compat_best": ["ENFP", "ENTP"], "compat_worst": ["ESTP", "ESFP"], "jobs": ["상담심리사", "작가", "인권활동가", "교사"]},
    "INTJ": {"nickname": "용의주도한 전략가", "keywords": ["전략적", "독립적", "분석적"], "strengths": ["장기계획", "논리력", "결단력"], "weaknesses": ["과도한 비판", "감정표현 어려움"], "compat_best": ["ENFP", "ENTP"], "compat_worst": ["ESFP", "ESFJ"], "jobs": ["전략기획가", "과학자", "데이터분석가", "건축가"]},
    "ISTP": {"nickname": "만능 재주꾼", "keywords": ["실용적", "논리적", "독립적"], "strengths": ["문제해결", "적응력", "냉철함"], "weaknesses": ["감정표현 부족", "장기계획 약함"], "compat_best": ["ESFJ", "ESTJ"], "compat_worst": ["ENFJ", "INFJ"], "jobs": ["엔지니어", "정비기술자", "파일럿", "프로그래머"]},
    "ISFP": {"nickname": "호기심 많은 예술가", "keywords": ["예술적", "온화함", "유연함"], "strengths": ["미적감각", "공감력", "적응력"], "weaknesses": ["갈등회피", "계획성 부족"], "compat_best": ["ESFJ", "ESTJ"], "compat_worst": ["ENTJ", "INTJ"], "jobs": ["디자이너", "포토그래퍼", "요리사", "플로리스트"]},
    "INFP": {"nickname": "열정적인 중재자", "keywords": ["이상주의", "창의적", "공감능력"], "strengths": ["창의성", "가치중심", "공감"], "weaknesses": ["현실감 부족", "비판에 민감"], "compat_best": ["ENFJ", "ENTJ"], "compat_worst": ["ESTJ", "ISTJ"], "jobs": ["작가", "카피라이터", "상담사", "예술가"]},
    "INTP": {"nickname": "논리적인 사색가", "keywords": ["논리적", "독창적", "분석적"], "strengths": ["창의적사고", "논리력", "호기심"], "weaknesses": ["사회성 부족", "실행력 약함"], "compat_best": ["ENTJ", "ENFJ"], "compat_worst": ["ESFJ", "
